---
title: "Quick Start: Installation Instructions"
---

## R

1. R is available for free from the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/). Go to this website.
2. Click the download link that corresponds to your operating system.
   - **Windows** Click "Base" and download the installer. Follow the installation instructions.
   - **Mac** Select the version that corresponds with the version of your operating system and chip type (silicon vs. Intel). Follow the installation instructions.
   - **Linux** Click on your distribution. Follow the installation instructions.
  
Confirm that installation was successful by opening the R program.

## RStudio

While the R application is perfectly functional on its own, it is not as convenient as other applications. Specifically, we are interested in a more user-friendly Graphical User Interface (GUI). The GUI comprises the menus available to users for point-and-click operations. RStudio is a free software with an accessible GUI.

1. Navigate to the [RStudio IDE webpage](https://www.rstudio.com/products/rstudio/download/).
2. Choose the free version of RStudio Desktop.
3. Select your operating system and follow the installation instructions.

Confirm that the installation was successful by opening RStudio.

## Aggie Virtual Desktop

[Aggie Virtual Desktop](https://it.tamu.edu/oal/aggie-virtual-desktop/index.php), also known as the Virtual Open Access Lab (VOAL) provides access to software, including R. This is an option if you cannot download R or RStudio onto your computer.

1. Navigate to the [Aggie Virtual Desktop login page](https://aggievirtualdesktop.tamu.edu/).
2. You can either download the VMware Horizon Client or access VMware Horizon via an internet browser.
3. Click on `VOAL`. Make sure you allow for pop-up windows.
4. You can access R and RStudio through the virtual machine (VM).

