project:
  type: book

book:
  cover-image: cover.png
  cover-image-alt: |
      cover image for Data Science for Economic and Social Issues: Notes for ECON470 at Texas A&M University by Anna Ziff
  title: "Data Science for Economic and Social Issues"
  author: "Anna Ziff"
  date: "2025/6/19"
  chapters:
    - index.qmd
    
    - part: "Setup"
      chapters:
        - 01_Installation.qmd
        - 02_Setup.qmd
        - 03_Command_Line_and_Git.qmd
        
    - part: "R and R Markdown Basics"
      chapters: 
        - 04_R_Basics.qmd
        - 05_R_Markdown.qmd
        - 06_Structure.qmd
        
    - part: "Cleaning and Describing Data"
      chapters: 
        - 07_Data_Loading_Saving.qmd
        - 08_Data_Management.qmd
        - 09_Merging_and_Reshaping_Data.qmd
        - 10_Summary_Statistics.qmd
        - 11_Graphs.qmd
        - 12_Geographic_Data_and_Mapping.qmd
        
    - part: "Statistical Methods and Econometrics"
      chapters: 
        - 13_CLT.qmd
        - 14_Inference.qmd
        - 15_Regression.qmd
        - 16_Program_Evaluation.qmd
        - 17_Instrumental_Variables.qmd
        - 18_Discontinuity_Designs.qmd
        - 19_Difference_in_Differences.qmd
        - 20_EventStudies.qmd
        - 21_MachineLearning.qmd

    
bibliography: R-for-Economists.bib

format:
  html:
    theme: 
       - cosmo
       - custom.scss
    include-in-header: 
       - aria_label.html
       - text: |
           <script src="scroll-access.js"></script>
    include-after-body: 
       - fix_header.html
    highlight-style: github
    toc: true
    number-sections: true
    code-fold: false
    math: mathjax
    
    
editor: visual

