
# Preface {.unnumbered}

This website contains the notes for ECON 470: Data Science for Economic and Social Issues taught at Texas A&M University. This course includes instruction in:

* using R, and by extension computer programming tenants;

* the responsible use and management of data including data cleaning and description;

* methods in causal analysis that economists, policymakers, and decision-makers rely on to draw conclusions, not only about the world, but also about how to make changes the world.


These notes are designed to be used alongside other instructional material available on Canvas and Charles Wheelan's book, _Naked Statistics: Stripping the dread from the data_. 

In preparing these materials, I referred to several online resources. This includes both for content and for practice exercise ideas. At the end of each chapter, I list the resources I used. I thank Xinqi Xu for creating this website and ensuring it meets accessibility requirements. All errors are my own. Please email me (aziff "at" tamu.edu) so that I can rectify them.

